## Values for azure-dev environment
## Usage: helm install talk ./chart/talk -n talk-dev -f chart/values-dev.yaml

global:
  environment: dev
  domain: talk.dev.telodev.com
  zitadelDomain: zitadel.dev.telodev.com
  adminEmail: admin@telodev.com

tls:
  enabled: true
  clusterIssuer: letsencrypt-prod

registry:
  server: talkdevacr.azurecr.io

externalSecrets:
  keyVaultUrl: https://talk-dev-vault.vault.azure.net/
  workloadIdentity:
    clientId: 15656477-0f53-44b8-9cd2-955bb4ef69ef
    tenantId: 9865568e-ab2b-4e9e-844e-b8047f9babda

apps:
  consoleWeb:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa
  adminWeb:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa
  agentsWeb:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa

services:
  authz:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa
  consoleApi:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa
  identitySync:
    image:
      tag: ae38654663a74aa6160c5cb5c4783bf74e654bfa
