apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: talk-azure-key-vault
  labels:
    {{- include "talk.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.externalSecrets.keyVaultUrl }}
      serviceAccountRef:
        name: talk-external-secrets-workload-identity
        namespace: external-secrets
