apiVersion: v1
kind: ServiceAccount
metadata:
  name: talk-external-secrets-workload-identity
  namespace: external-secrets
  labels:
    {{- include "talk.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.externalSecrets.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.externalSecrets.workloadIdentity.tenantId }}
