{{- if eq .Values.cloud "azure" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: talk-external-secrets-workload-identity
  namespace: external-secrets
  labels:
    {{- include "talk.labels" . | nindent 4 }}
  annotations:
    {{- include "talk.workloadIdentityAnnotations" (list $ .Values.externalSecrets.workloadIdentity) | nindent 4 }}
{{- end }}
