apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-config
  labels:
    {{- include "talk.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: talk-azure-key-vault
  target:
    name: zitadel-config
    creationPolicy: Owner
  data:
    - secretKey: masterkey
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "masterkey") }}
    - secretKey: database-dsn
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-dsn") }}
    - secretKey: database-host
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-host") }}
    - secretKey: database-port
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-port") }}
    - secretKey: database-name
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-name") }}
    - secretKey: database-user
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-user") }}
    - secretKey: database-password
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "database-password") }}
    - secretKey: admin-password
      remoteRef:
        key: {{ include "talk.kvKey" (list $ "zitadel" "admin-password") }}
