apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: talk-envoy-proxy
  labels:
    {{- include "talk.labels" . | nindent 4 }}
spec:
  provider:
    type: Kubernetes
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
  labels:
    {{- include "talk.labels" . | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
