{{- $root := . }}
{{- range $tier, $tierConfig := .Values.oauth2Proxy.tiers }}
{{- if $tierConfig.enabled }}
{{- include "talk.oauth2Proxy.configmap" (dict "root" $root "tier" $tier "tierConfig" $tierConfig) }}
---
{{ include "talk.oauth2Proxy.externalSecret" (dict "root" $root "tier" $tier) }}
---
{{ include "talk.oauth2Proxy.deployment" (dict "root" $root "tier" $tier "tierConfig" $tierConfig) }}
---
{{ end }}
{{ end }}
