apiVersion: v1
kind: Service
metadata:
  name: authz
  labels:
    app.kubernetes.io/name: authz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authz
  ports:
    - name: http
      port: 8000
      targetPort: http
