apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talk-services-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GITOPS_REPO_URL
    targetRevision: main
    path: services/overlays/azure-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: talk-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
