apiVersion: v1
kind: Service
metadata:
  name: talk-host-postgres
  namespace: talk-local
  labels:
    app.kubernetes.io/name: talk-host-postgres
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
