apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ../../base
  - vault-secretstore.yaml
  - host-postgres.yaml
  - zitadel-external-secret.yaml
patches:
  - target:
      kind: Deployment
      name: zitadel
    patch: |-
      - op: add
        path: /metadata/namespace
        value: talk-local
  - target:
      kind: Service
      name: zitadel
    patch: |-
      - op: add
        path: /metadata/namespace
        value: talk-local
