apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-config
  namespace: talk-local
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: talk-hashicorp-vault
  target:
    name: zitadel-config
    creationPolicy: Owner
  data:
    - secretKey: masterkey
      remoteRef:
        key: talk/local/zitadel/config
        property: masterkey
    - secretKey: database-dsn
      remoteRef:
        key: talk/local/zitadel/config
        property: database-dsn
    - secretKey: database-host
      remoteRef:
        key: talk/local/zitadel/config
        property: database-host
    - secretKey: database-port
      remoteRef:
        key: talk/local/zitadel/config
        property: database-port
    - secretKey: database-name
      remoteRef:
        key: talk/local/zitadel/config
        property: database-name
    - secretKey: database-user
      remoteRef:
        key: talk/local/zitadel/config
        property: database-user
    - secretKey: admin-password
      remoteRef:
        key: talk/local/zitadel/config
        property: admin-password
