apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: talk-azure-key-vault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://replace-with-talk-key-vault.vault.azure.net
      serviceAccountRef:
        name: talk-external-secrets-workload-identity
        namespace: external-secrets
