apiVersion: v1
kind: ServiceAccount
metadata:
  name: talk-external-secrets-workload-identity
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: replace-with-managed-identity-client-id
    azure.workload.identity/tenant-id: replace-with-tenant-id
