apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talk-dev
resources:
  - ../../base
  - zitadel-external-secret.yaml
patches:
  - path: zitadel-patches.yaml
    target:
      kind: Deployment
      name: zitadel
