apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
spec:
  template:
    spec:
      initContainers:
        - name: init-schema
          env:
            - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
              value: require
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
              value: require
      containers:
        - name: api
          env:
            - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
              value: require
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
              value: require
            - name: ZITADEL_EXTERNALDOMAIN
              value: zitadel.dev.telodev.com
            - name: ZITADEL_EXTERNALPORT
              value: "443"
            - name: ZITADEL_EXTERNALSECURE
              value: "true"
            - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS
              value: admin@telodev.com
            - name: ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI
              value: https://zitadel.dev.telodev.com/ui/v2/login/
            - name: ZITADEL_OIDC_DEFAULTLOGINURLV2
              value: https://zitadel.dev.telodev.com/ui/v2/login/login?authRequest=
            - name: ZITADEL_OIDC_DEFAULTLOGOUTURLV2
              value: https://zitadel.dev.telodev.com/ui/v2/login/logout?post_logout_redirect=
            - name: ZITADEL_SAML_DEFAULTLOGINURLV2
              value: https://zitadel.dev.telodev.com/ui/v2/login/login?samlRequest=
        - name: login
          env:
            - name: CUSTOM_REQUEST_HEADERS
              value: Host:zitadel.dev.telodev.com,X-Forwarded-Proto:https
