apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: talk-azure-key-vault
  target:
    name: oauth2-proxy-oidc
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: talk-dev-oauth2-proxy-client-id
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: talk-dev-oauth2-proxy-client-secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: talk-dev-oauth2-proxy-cookie-secret
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: talk-dev-zitadel-issuer-url
    - secretKey: OAUTH2_PROXY_REDIRECT_URL
      remoteRef:
        key: talk-dev-oauth2-proxy-redirect-url
    - secretKey: OAUTH2_PROXY_COOKIE_DOMAIN
      remoteRef:
        key: talk-dev-oauth2-proxy-cookie-domain
    - secretKey: OAUTH2_PROXY_WHITELIST_DOMAIN
      remoteRef:
        key: talk-dev-oauth2-proxy-whitelist-domain
    - secretKey: OAUTH2_PROXY_COOKIE_SECURE
      remoteRef:
        key: talk-dev-oauth2-proxy-cookie-secure
    - secretKey: OAUTH2_PROXY_INSECURE_SKIP_ISSUER_VERIFICATION
      remoteRef:
        key: talk-dev-oauth2-proxy-insecure-skip-issuer-verification
