apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-config
  namespace: talk-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: talk-azure-key-vault
  target:
    name: zitadel-config
    creationPolicy: Owner
  data:
    - secretKey: masterkey
      remoteRef:
        key: talk-prod-zitadel-masterkey
    - secretKey: database-dsn
      remoteRef:
        key: talk-prod-zitadel-database-dsn
    - secretKey: database-host
      remoteRef:
        key: talk-prod-zitadel-database-host
    - secretKey: database-port
      remoteRef:
        key: talk-prod-zitadel-database-port
    - secretKey: database-name
      remoteRef:
        key: talk-prod-zitadel-database-name
    - secretKey: database-user
      remoteRef:
        key: talk-prod-zitadel-database-user
    - secretKey: admin-password
      remoteRef:
        key: talk-prod-zitadel-admin-password
