apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talk-local
resources:
  - ../../base
  - external-secrets.yaml
images:
  - name: ghcr.io/talk/authz
    newTag: local
  - name: ghcr.io/talk/identity-sync
    newTag: local
  - name: ghcr.io/talk/console-api
    newTag: local
