apiVersion: v1
kind: Service
metadata:
  name: identity-sync
  labels:
    app.kubernetes.io/name: identity-sync
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity-sync
  ports:
    - name: http
      port: 8000
      targetPort: http
