apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talk-services-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/talk/talk-platform-gitops.git
    targetRevision: main
    path: services/overlays/azure-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: talk-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
