apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talk-dev
resources:
  - ../../base
  - external-secrets.yaml
images:
  - name: ghcr.io/talk/authz
dentity-sync$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
onsole-api$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
uthz$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
    newTag: dev
  - name: ghcr.io/talk/identity-sync
dentity-sync$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
onsole-api$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
uthz$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
    newTag: dev
  - name: ghcr.io/talk/console-api
dentity-sync$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
onsole-api$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
uthz$/{n;s|newTag:.*|newTag: a578d18f3439e1fe35dee4068f76c979cda36c32|}
    newTag: dev
